### PR TITLE
feat(jest_unit_test): updated node version to 16.x

### PR DESCRIPTION
**Pull request by danilosantos2908**
#### What does this PR do?

Updates the node version to 16 on the jest action file. More on: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

I didn't update the other actions in this repository not to cause a general change in all pipelines. Let's first test the effect on unit testing pipelines. I recommend creating one card for each warning to test in isolation.

#### How does this PR tested?
I'm not very familiar with Github Actions as I am with Bitbucket & Gitlab, where I know that it would be possible to test this without merging. So, let's merge to test the pipelines on the other repos. If anything goes wrong, we can always revert. I'm open to suggestions on this matter.

### CODE REVIEW

**Comment by AsadShakeel** [comment]
I don't think that I can provide any review on this matter for now.

**Comment by aleCeres** [comment]
@danilosantos2908 I like your strategy. My suggestion is to write in each pr the repo involved into, so that we can trigger after the merge of this PR, one ci for each repo involved. 👍 
What do you think guys?

**Comment by AsadShakeel** [comment]
I'm blank on writing the pipelines, but if you give me a starting point to think of, I can surely see and may recommend something!

**Comment by aleCeres** [comment]
> I'm blank on writing the pipelines, but if you give me a starting point to think of, I can surely see and may recommend something!

Sure. I ll provide you context tomorrow!

**Review by AsadShakeel — APPROVED** [review]

**Review by aleCeres — APPROVED** [review]

**Pull request merged**
